Repository SwaprHQ/swapr-dapp, pull requests merged in 2022-03, with the labels that each got.

#721 feature: add GitHub Issues and PR templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/epic.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/other.md
  .github/pull_request_template.md
Labels: enhancement

#782 Added Stats to the Navigation
  src/components/Header/index.tsx
Labels: bug

#711 [Feature] New swapbox design
  public/locales/en.json
  src/assets/svg/eco-router.svg
  src/assets/svg/mev-protection.svg
  src/assets/svg/recipient.svg
  src/assets/svg/slippage.svg
  src/assets/svg/sushiswap-new-logo.svg
  src/assets/svg/swap-icon.svg
  src/components/Button/index.tsx
  src/components/CurrencyInputPanel/index.tsx
  src/components/FiatValueDetails/index.tsx
  src/components/Pool/LiquidityMiningCampaignView/StakeCard/ConfirmClaimModal/Header/index.tsx
  src/components/Pool/LiquidityMiningCampaignView/StakeCard/ModalBase/Header/index.tsx
  src/components/Pool/LiquidityMiningCampaignView/StakeCard/index.tsx
  src/components/RecipientField/index.tsx
  src/components/swap/SwapButton.tsx
  src/components/swap/SwapSettings.tsx
  src/components/swap/Tabs.tsx
  src/components/swap/TradePrice.tsx
  src/components/swap/styleds.tsx
  src/constants/index.tsx
  src/hooks/useUSDValue.ts
  src/pages/AddLiquidity/index.tsx
  src/pages/Bridge/Tabs.tsx
  src/pages/Bridge/index.tsx
  src/pages/RemoveLiquidity/index.tsx
  src/pages/Swap/index.tsx
  src/theme/index.tsx
  src/theme/styled.d.ts
  src/utils/computeFiatValuePriceImpact.ts
  src/utils/prices.ts
Labels: Epic

#826 test: Smoke Test for Liquidity page
  src/pages/Pools/index.tsx
  tests/cypress/integration/smoke/liquidityTests.ts
  tests/pages/LiquidityPage.ts
  yarn.lock
Labels: UI Automation | QA
