Repository SwaprHQ/swapr-dapp, pull requests merged in 2022-10, with the labels that each got.

#1547 release: v1.0.0-beta.16.1
  .env.development
  .env.development.local
  .github/workflows/ci.yml
  .gitignore
  Dockerfile
  config-overrides.js
  docker-compose.yml
  package.json
  public/index.html
  src/analytics/provider/analytics.provider.tsx
  src/assets/images/DxDaoProductBanner.svg
  src/assets/images/cow-protocol.svg
  src/assets/images/routing-cow.svg
  src/components/Button/Button.tsx
  src/components/Claim/ClaimModal.tsx
  src/components/Header/MobileOptions.tsx
  src/components/Header/index.tsx
  src/components/PageMetaData/PageMetaData.tsx
  src/components/PageMetaData/index.tsx
  src/components/Routing/RouteCheck.tsx
  src/components/WalletModal/index.tsx
  src/hooks/useEnvironment.ts
  src/index.tsx
  src/lib/eco-router/api.ts
  src/pages/Account/Account.tsx
  src/pages/AddLiquidity/index.tsx
  src/pages/App.tsx
  src/pages/Bridge/index.tsx
  src/pages/GovPages/index.tsx
  src/pages/LiquidityMining/Create/index.tsx
  src/pages/Pools/LiquidityMiningCampaign/index.tsx
  src/pages/Pools/Pair/index.tsx
  src/pages/Pools/index.tsx
  src/pages/RemoveLiquidity/index.tsx
  src/pages/Rewards/index.tsx
  src/pages/Swap/index.tsx
  src/utils/ui-constants.js
  start-tests.sh
  tests/pages/BridgePage.ts
  tests/pages/MenuBar.ts
  tests/pages/NetworkSwitcher.ts
  tests/pages/SwapPage.ts
  tests/pages/TokenMenu.ts
  tests/support/index.js
  tests/synpress/.eslintrc.js
  tests/synpress/specs/01transactionless/walletInteraction/SwitchingNetworkTests.ts
  tests/synpress/specs/01transactionless/walletInteraction/WalletConnectionTests.ts
  tests/synpress/specs/02transactionfull/bridge/BridgeTests.ts
  tests/synpress/specs/02transactionfull/rewards/CreatingCampaignTests.ts
  tests/synpress/specs/02transactionfull/swap/SwapTests.ts
  tests/synpress/specs/02transactionfull/swap/WrapTests.ts
  tests/synpress/synpress.config.ts
  tests/synpress/synpress.json
  tests/synpress/tsconfig.json
  tests/utils/MetamaskNetworkHandler.ts
  tests/utils/enums/ChainsEnum.ts
  yarn.lock
Labels: ready-for-tests, ready-for-synpress-tests

#1549 Fixed label checker in CI
  .github/workflows/ci.yml
Labels: QA

#1513 update DoubleCurrencyLogo folder name to match component and fix import
  src/components/CurrencyInputPanel/CurrencyView.tsx
  src/components/DoubleCurrencyLogo/DoubleCurrencyLogo.tsx
  src/components/DoubleCurrencyLogo/index.tsx
  src/components/LiquidityMining/Create/Steps/PairAndReward/AssetSelector/AssetLogo.tsx
  src/components/Pool/LiquidityMiningCampaignView/Information/index.tsx
  src/components/Pool/LoadingGrid/LoadingCard/LoadingCard.tsx
  src/components/Pool/PairsList/CampaignCard/index.tsx
  src/components/Pool/PairsList/LoadingList/LoadingRow/LoadingRow.tsx
  src/components/Pool/PairsList/Pair/Pair.tsx
  src/components/PositionCard/index.tsx
  src/components/SearchModal/PairList/PairList.tsx
  src/pages/AddLiquidity/index.tsx
  src/pages/GovPages/Card.tsx
  src/pages/Pools/LiquidityMiningCampaign/index.tsx
  src/pages/Pools/Pair/index.tsx
  src/pages/RemoveLiquidity/index.tsx
  src/pages/Rewards/index.tsx
Labels: ready-for-synpress-tests

#1519 Refactor and remove unused components
  src/components/Footer/index.tsx
  src/components/NavigationTabs/index.tsx
  src/components/Pool/PoolLiquidityHeader/PoolLiquidityHeader.tsx
  src/components/Pool/PoolLiquidityHeader/index.tsx
  src/pages/App.tsx
  src/pages/Pools/AddLiquidity/ConfirmAddModalBottom.tsx
  src/pages/Pools/AddLiquidity/PoolPriceBar.tsx
  src/pages/Pools/AddLiquidity/ProtocolFeeBar.tsx
  src/pages/Pools/AddLiquidity/index.tsx
  src/pages/Pools/AddLiquidity/redirects.tsx
  src/pages/Pools/LiquidityMiningCampaign/index.tsx
  src/pages/Pools/RemoveLiquidity/PoolPriceBar.tsx
  src/pages/Pools/RemoveLiquidity/index.tsx
  src/pages/Pools/RemoveLiquidity/redirects.tsx
  src/pages/Pools/index.tsx
  src/pages/Rewards/index.tsx
  src/pages/Routes.tsx
  src/pages/Swap/index.tsx
Labels: ready-for-tests, ready-for-synpress-tests

#1560 Fix for docker test runner
  Dockerfile
Labels: QA

#1561 Add MIVA token to tokenlist
  src/constants/index.tsx
Labels: QA

#1558 Remove unused locales
  public/locales/de/bridge.json
  public/locales/de/liquidity.json
  public/locales/de/pool.json
  public/locales/de/swap.json
  public/locales/en-US/account.json
  public/locales/en-US/bridge.json
  public/locales/en-US/common.json
  public/locales/en-US/liquidity.json
  public/locales/en-US/pool.json
  public/locales/en-US/swap.json
  public/locales/es-AR/bridge.json
  public/locales/es-AR/liquidity.json
  public/locales/es-AR/pool.json
  public/locales/es-AR/swap.json
  public/locales/es-US/bridge.json
  public/locales/es-US/liquidity.json
  public/locales/es-US/pool.json
  public/locales/es-US/swap.json
  public/locales/it/bridge.json
  public/locales/it/liquidity.json
  public/locales/it/pool.json
  public/locales/it/swap.json
  public/locales/iw/bridge.json
  public/locales/iw/liquidity.json
  public/locales/iw/pool.json
  public/locales/iw/swap.json
  public/locales/ro/bridge.json
  public/locales/ro/liquidity.json
  public/locales/ro/pool.json
  public/locales/ro/swap.json
  public/locales/ru/bridge.json
  public/locales/ru/liquidity.json
  public/locales/ru/pool.json
  public/locales/ru/swap.json
  public/locales/vi/bridge.json
  public/locales/vi/liquidity.json
  public/locales/vi/pool.json
  public/locales/vi/swap.json
  public/locales/zh-CN/bridge.json
  public/locales/zh-CN/liquidity.json
  public/locales/zh-CN/pool.json
  public/locales/zh-CN/swap.json
  public/locales/zh-TW/bridge.json
  public/locales/zh-TW/liquidity.json
  public/locales/zh-TW/pool.json
  public/locales/zh-TW/swap.json
Labels: QA

#1566 add socketscan to getExplorerLink function
  src/pages/Account/TransactionRows/BridgeTransactionRow.tsx
  src/pages/Bridge/BridgeTransactionsSummary.tsx
  src/utils/index.ts
Labels: QA

#1504 Feature/1471 bsc chain
  package.json
  src/assets/images/binance-chain-logo.svg
  src/assets/images/bnb-logo.png
  src/assets/images/bunny-mono.png
  src/assets/images/curve-logo.svg
  src/assets/images/routing-curve.png
  src/assets/images/routing-curve.svg
  src/assets/images/routing-pancakeswap.svg
  src/components/CurrencyLogo/CurrencyLogo.utils.ts
  src/components/NetworkSwitcher/NetworkSwitcher.preset.ts
  src/components/Swap/SwapButtons/SwapButton.tsx
  src/components/Web3Status/AccountStatus.tsx
  src/connectors/index.ts
  src/constants/index.tsx
  src/constants/lists.ts
  src/hooks/useUSDValue.ts
  src/lib/eco-router/platforms.ts
  src/pages/GovPages/constant.ts
  src/services/EcoBridge/Connext/Connext.lists.ts
  src/services/EcoBridge/Connext/Connext.ts
  src/services/EcoBridge/EcoBridge.config.ts
  src/services/EcoBridge/Socket/Socket.test.ts
  src/services/EcoBridge/Socket/Socket.utils.ts
  src/services/EcoBridge/Xdai/XdaiBridge.ts
  src/services/EcoBridge/Xdai/XdaiBridge.utils.ts
  src/state/lists/hooks.ts
  src/theme/index.tsx
  src/utils/chainSupportsSWPR.ts
  src/utils/coingecko.ts
  src/utils/index.ts
  src/utils/ui-constants.js
  tests/synpress/.eslintrc.js
  yarn.lock
Labels: Network

#1567 fix connext bridge on optimism chain
  src/services/EcoBridge/Connext/Connext.config.ts
  src/services/EcoBridge/Connext/Connext.lists.ts
  src/services/EcoBridge/Connext/Connext.ts
  src/services/EcoBridge/EcoBridge.config.ts
  src/services/EcoBridge/Socket/Socket.utils.ts
Labels: QA
