Repository SwaprHQ/swapr-dapp, pull requests merged in 2022-08, with the labels that each got.

#1259 Fix expiring quotes
  src/state/swap/hooks.ts
Labels: bug

#1280 feature: update CoWTrade
  package.json
  src/components/TransactionConfirmationModal/index.tsx
  src/components/swap/SwapButtons/SwapButtons.tsx
  src/components/swap/TradeDetails.tsx
  src/hooks/useApproveCallback.ts
  src/hooks/useSwapCallback.ts
  src/lib/eco-router/api.ts
  src/lib/eco-router/hooks.ts
  src/lib/eco-router/types.ts
  src/pages/Swap/index.tsx
  src/state/swap/hooks.ts
  src/state/transactions/updater.tsx
  src/utils/prices.ts
  yarn.lock
Labels: Eco Router

#1337 Fix/static provider
  src/state/swap/hooks.ts
Labels: Dev/QA Attention

#1347 Fix: 1344 add spacing for the text in swap button
  src/components/swap/SwapButtons/SwapButton.tsx
Labels: Dev/QA Attention

#1341 fix: approval disabled
  src/pages/Swap/index.tsx
Labels: Dev/QA Attention

#1345 fix: use native currency price
  src/hooks/useUSDValue.ts
  src/utils/coingecko.ts
Labels: Dev/QA Attention

#1346 Fix: 1343 set only on mobile smaller logo and bigger gap for settings
  src/components/Header/index.tsx
  src/components/SwaprVersionLogo/index.tsx
Labels: Dev/QA Attention

#1340 Add currency logo next to pooled tokens on User Liquidity
  public/locales/de/pool.json
  public/locales/en-US/pool.json
  public/locales/en/pool.json
  public/locales/es-AR/pool.json
  public/locales/es-US/pool.json
  public/locales/it/pool.json
  public/locales/iw/pool.json
  public/locales/ro/pool.json
  public/locales/ru/pool.json
  public/locales/vi/pool.json
  public/locales/zh-CN/pool.json
  public/locales/zh-TW/pool.json
  src/components/Pool/PairView/UserLiquidity/UserLiquidity.tsx
  src/components/Pool/PairView/ValueWithLabel/ValueWithLabel.tsx
Labels: enhancement

#1333 Fix inconsistent 24h volume on liquidity page
  src/apollo/client.ts
  src/hooks/usePairVolume24hUSD.ts
  yarn.lock
Labels: bug
