Repository SwaprHQ/swapr-dapp, pull requests merged in 2022-11, with the labels that each got.

#1575 feature: show three decimals on bridge box
  src/services/EcoBridge/Arbitrum/ArbitrumBridge.tsx
  src/services/EcoBridge/Connext/Connext.ts
  src/services/EcoBridge/EcoBridge.utils.tsx
  src/services/EcoBridge/OmniBridge/OmniBridge.ts
  src/services/EcoBridge/Socket/SocketBridge.ts
  src/services/EcoBridge/Xdai/XdaiBridge.ts
Labels: QA

#1420 Feature/add simple chart
  package.json
  public/locales/en/common.json
  public/locales/en/simpleChart.json
  src/apollo/client.ts
  src/assets/images/chart-loading.svg
  src/components/Button/Button.tsx
  src/components/ButtonGroup/ButtonGroup.stories.mdx
  src/components/ButtonGroup/ButtonGroup.tsx
  src/components/Charts/AreaChartTokenPrice.stories.mdx
  src/components/Charts/AreaChartTokenPrice.tsx
  src/components/Charts/chartMockData.json
  src/components/Charts/chartUtils.ts
  src/components/Charts/useChart.ts
  src/components/PercentualDifference/PercentualDifferenceText.tsx
  src/components/PercentualDifference/percentualDifference.tsx
  src/components/SimpleChart/ShowChart.tsx
  src/components/SimpleChart/SimpleChart.stories.mdx
  src/components/SimpleChart/SimpleChart.tsx
  src/components/SimpleChart/SimpleChartContainer.tsx
  src/components/SimpleChart/SimpleChartDateFilters.tsx
  src/components/SimpleChart/SimpleChartLoading.tsx
  src/components/Swap/ChartTabs.tsx
  src/components/Swap/Tabs.tsx
  src/constants/features.ts
  src/hooks/usePairTokenPriceByTimestamp.ts
  src/pages/AppBody.tsx
  src/pages/Swap/ChartToggle.tsx
  src/pages/Swap/index.tsx
  src/state/user/actions.ts
  src/state/user/hooks.tsx
  src/state/user/reducer.ts
  yarn.lock
Labels: Feature

#1569 Feature/eco bridge reducer cleanup
  src/services/EcoBridge/Arbitrum/ArbitrumBridge.reducer.ts
  src/services/EcoBridge/Arbitrum/ArbitrumBridge.selectors.ts
  src/services/EcoBridge/Arbitrum/ArbitrumBridge.tsx
  src/services/EcoBridge/Arbitrum/ArbitrumBridge.types.ts
  src/services/EcoBridge/Connext/Connext.reducer.ts
  src/services/EcoBridge/Connext/Connext.selectors.ts
  src/services/EcoBridge/Connext/Connext.ts
  src/services/EcoBridge/Connext/Connext.types.ts
  src/services/EcoBridge/EcoBridge.ts
  src/services/EcoBridge/EcoBridge.types.ts
  src/services/EcoBridge/EcoBridge.utils.tsx
  src/services/EcoBridge/OmniBridge/OmniBridge.reducers.ts
  src/services/EcoBridge/OmniBridge/OmniBridge.selectors.ts
  src/services/EcoBridge/OmniBridge/OmniBridge.ts
  src/services/EcoBridge/OmniBridge/OmniBridge.types.ts
  src/services/EcoBridge/Socket/Socket.reducer.ts
  src/services/EcoBridge/Socket/Socket.selectors.ts
  src/services/EcoBridge/Socket/Socket.types.ts
  src/services/EcoBridge/Socket/SocketBridge.ts
  src/services/EcoBridge/Xdai/XdaiBridge.reducer.ts
  src/services/EcoBridge/Xdai/XdaiBridge.selectors.ts
  src/services/EcoBridge/Xdai/XdaiBridge.ts
  src/services/EcoBridge/store/EcoBridge.selectors.ts
Labels: QA

#1589 Fix: pools create/add/remove modal has incorrect width
  src/pages/AppBody.tsx
Labels: bug
